### ISSUE TITLE
Addition of a Manuals and documents page within the Glider Lab 

### ISSUE THREAD

**Issue by acossio** [SWFSC/glider-lab-manual#1]
I think that we add a Manuals and Documents page. We have a lot of different sensors with manuals, and I think that they could have their own page. Otherwise, I'm open to having an index on the Glider lab page where you could click on the topic and it sends you down the page to it. I'm open to talking about it as well.

**Comment by acossio** [comment]
I see that there is indexing on the right side of the webpage so keeping Manuals and Documents all on the Lab page should work fine. No need to add a separate page.

**Comment by smwoodman** [comment]
Hey @acossio just a quick note saying I totally agree with this, and a soft suggestion to add subheadings under 'Manuals'. E.g., `### Slocum` and `### Cameras` so that they will show up in that indexing as well.
