### ISSUE TITLE
headings

### ISSUE THREAD

**Issue by smwoodman** [SWFSC/glider-lab-manual#2]
@acossio I was just browsing around the website, and fyi I think the headings in lab.qmd need to be updated? 

Specifically, unless you do want everything to be listed under 'Standard Operating Procedures', then the headings (eg [here](https://github.com/SWFSC/glider-lab-manual/blob/de2f3775b92c4d2c2f8efe0c602754f737ce3549/content/lab.qmd#L13) and [here](https://github.com/SWFSC/glider-lab-manual/blob/de2f3775b92c4d2c2f8efe0c602754f737ce3549/content/lab.qmd#L42)) need to be prefixed with the same number of '#'.

![image](https://github.com/user-attachments/assets/d10af25a-78b7-41c0-9fb1-cb145bf6e78a)

**Comment by acossio** [comment]
I just changed SOP to 2 pound signs so it matches the other headers. Thanks
