### ISSUE TITLE
Confirm member roles

### ISSUE THREAD

**Issue by smwoodman** [SWFSC/glider-lab-manual#4]
Hey @acossio, could you take a pass at updating the [team members](https://swfsc.github.io/glider-lab-manual/#team-members) roles? low priority, and also noted that this may be a Christian/Heidi thing to define.

**Comment by acossio** [comment]
I think that the team members and roles look good for now. As you say, when we have our discussion with Heidi and Christian, they may have input as well. Should we put what program each person is in?

**Comment by smwoodman** [comment]
Cool cool. For me, I don't think any need to get program-specific? Although recognized that I listed that out for Christian/Heidi.

I'll leave this open as a reminder to ask them about this next week.

**Comment by acossio** [comment]
Check my changes and see what you think.
