### ISSUE TITLE
Consider renaming .qmd files as .md

### ISSUE THREAD

**Issue by csbrown** [SWFSC/glider-lab-manual#9]
It looks like most of the markdown files in here are vanilla markdown and don't include any R.  If so, Github will render these in the browser if the extension is `.md` instead of `.qmd`.

**Comment by smwoodman** [comment]
Hey Scott - we're using [Quarto](https://quarto.org/docs/websites/)/GH Actions to render these files as a website at https://swfsc.github.io/glider-lab-manual/. 

So, accessing these files should happen through that website, rather than GitHub directly.
